### ISSUE TITLE
'ApiClient' object has no attribute 'pool'

### ISSUE THREAD

**Issue by MattBriden** [sergioteula/python-amazon-paapi#83]
Hi, I am using python-amazon-paapi 4.4.1 in an AWS lambda function and receiving the following error when instantiating the class.
```
[ERROR] OSError: [Errno 38] Function not implemented
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/src/handler.py", line 3, in <module>
    lambda_handler = injector.get(AmazonProxy).handler
  File "/var/task/injector/__init__.py", line 915, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/var/task/injector/__init__.py", line 276, in get
    return injector.create_object(self._cls)
  File "/var/task/injector/__init__.py", line 938, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/var/task/injector/__init__.py", line 969, in call_with_injection
    dependencies = self.args_to_inject(
  File "/var/task/injector/__init__.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "/var/task/injector/__init__.py", line 1017, in args_to_inject
    instance = self.get(interface)  # type: Any
  File "/var/task/injector/__init__.py", line 915, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/var/task/injector/__init__.py", line 308, in get
    return injector.call_with_injection(self._callable)
  File "/var/task/injector/__init__.py", line 978, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/var/task/src/proxy/injection.py", line 9, in amazon_api
    return PAAPI()
  File "/var/task/common/paapi/paapi.py", line 19, in __init__
    self._api = AmazonApi(
  File "/var/task/amazon_paapi/api.py", line 48, in __init__
    self._api = DefaultApi(key, secret, self._host, self._region)
  File "/var/task/amazon_paapi/sdk/api/default_api.py", line 55, in __init__
    api_client = ApiClient(access_key = access_key,
  File "/var/task/amazon_paapi/sdk/api_client.py", line 91, in __init__
    self.pool = ThreadPool()
  File "/var/lang/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/var/lang/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/var/lang/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/var/lang/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.8/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(Exception ignored in: <function ApiClient.__del__ at 0x7fdf158313a0>
Traceback (most recent call last):
File "/var/task/amazon_paapi/sdk/api_client.py", line 106, in __del__
self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
```
A few things to note:
Firstly, I am running this in an AL2 (Python 3.8) Lambda function. At first I packaged the lambda natively on my OSX machine but after I received the error I built it in an AL2 docker container. Unfortunately this did not fix the error.

Secondly, this works perfectly when I run the code on my local machine, so perhaps I am missing pulling in a package when building my lambda function. Below is my file structure for the lambda function.
![Screen Shot 2021-11-12 at 7 45 43 PM](https://user-images.githubusercontent.com/30605575/141598996-2a158738-2da5-4717-a771-cb1b085a2194.png)

Let me know if I can provide any other useful information, thanks in advance!

**Comment by MattBriden** [comment]
I am closing this issue because it is seemingly a limitation of AWS Lambda and not this library https://stackoverflow.com/questions/34005930/multiprocessing-semlock-is-not-implemented-when-running-on-aws-lambda.
