### ISSUE TITLE
Json Decode Error

### ISSUE THREAD

**Issue by Falcone8** [sergioteula/python-amazon-paapi#84]
Traceback (most recent call last):
  File "/Users/Downloads/AmazonBot-1.1.0/main.py", line 11, in <module>
    from utils.product_amazon import product
  File "/Users/Downloads/AmazonBot-1.1.0/utils/product_amazon.py", line 8, in <module>
    config = json.load(config_file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 4 column 3 (char 69)

**Comment by Falcone8** [comment]
Excuse for the error

**Comment by sergioteula** [comment]
No problem!
